/*******************************************************/
/**  Autogenerated phoneset trees for cmu_dari    */
/*******************************************************/

#include "cst_string.h"
#include "cst_phoneset.h"
extern const cst_phoneset cmu_dari_phoneset;


static const char * const cmu_dari_featnames[] = {
 "vc",
 "vlng",
 "vheight",
 "vfront",
 "vrnd",
 "ctype",
 "cplace",
 "cvox",
 NULL };

static const char * const cmu_dari_phonenames[] = {
 "pau",
 "s",
 "e",
 "p",
 "a",
 "t",
 "o",
 "l",
 "j",
 "b",
 "U",
 "u",
 "k",
 "h",
 "A",
 "r",
 "m",
 "z",
 "w",
 "q",
 "d",
 "E",
 "dZ",
 "i",
 "n",
 "f",
 "g",
 "S",
 "Q",
 "x",
 "N",
 "tS",
 "G",
 "Z",
 NULL };

static const int cmu_dari_fv_000[] = { 0, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_dari_fv_001[] = { 0, 1, 0, 0, 0, 2, 3, 0,   -1 };
static const int cmu_dari_fv_002[] = { 4, 5, 6, 7, 0, 1, 1, 0,   -1 };
static const int cmu_dari_fv_003[] = { 0, 1, 0, 0, 0, 5, 8, 0,   -1 };
static const int cmu_dari_fv_004[] = { 4, 5, 7, 0, 0, 1, 1, 0,   -1 };
static const int cmu_dari_fv_005[] = { 0, 1, 0, 0, 0, 5, 9, 0,   -1 };
static const int cmu_dari_fv_006[] = { 4, 5, 6, 6, 4, 1, 1, 0,   -1 };
static const int cmu_dari_fv_007[] = { 0, 1, 0, 0, 0, 8, 3, 4,   -1 };
static const int cmu_dari_fv_008[] = { 0, 1, 0, 0, 0, 8, 10, 4,   -1 };
static const int cmu_dari_fv_009[] = { 0, 1, 0, 0, 0, 5, 8, 4,   -1 };
static const int cmu_dari_fv_010[] = { 4, 8, 0, 11, 4, 1, 1, 0,   -1 };
static const int cmu_dari_fv_011[] = { 4, 5, 0, 11, 4, 1, 1, 0,   -1 };
static const int cmu_dari_fv_012[] = { 0, 1, 0, 0, 0, 5, 12, 0,   -1 };
static const int cmu_dari_fv_013[] = { 0, 1, 0, 0, 0, 2, 13, 0,   -1 };
static const int cmu_dari_fv_014[] = { 4, 8, 0, 11, 0, 1, 1, 0,   -1 };
static const int cmu_dari_fv_015[] = { 0, 1, 0, 0, 0, 14, 3, 4,   -1 };
static const int cmu_dari_fv_016[] = { 0, 1, 0, 0, 0, 15, 1, 4,   -1 };
static const int cmu_dari_fv_017[] = { 0, 1, 0, 0, 0, 3, 3, 4,   -1 };
static const int cmu_dari_fv_018[] = { 0, 1, 0, 0, 0, 8, 8, 4,   -1 };
static const int cmu_dari_fv_019[] = { 0, 1, 0, 0, 0, 5, 1, 0,   -1 };
static const int cmu_dari_fv_020[] = { 0, 1, 0, 0, 0, 5, 9, 4,   -1 };
static const int cmu_dari_fv_021[] = { 4, 8, 6, 7, 0, 1, 1, 0,   -1 };
static const int cmu_dari_fv_022[] = { 0, 1, 0, 0, 0, 3, 3, 4,   -1 };
static const int cmu_dari_fv_023[] = { 4, 1, 0, 0, 0, 8, 3, 0,   -1 };
static const int cmu_dari_fv_024[] = { 0, 1, 0, 0, 0, 15, 3, 4,   -1 };
static const int cmu_dari_fv_025[] = { 0, 1, 0, 0, 0, 2, 16, 0,   -1 };
static const int cmu_dari_fv_026[] = { 0, 1, 0, 0, 0, 5, 12, 4,   -1 };
static const int cmu_dari_fv_027[] = { 0, 1, 0, 0, 0, 2, 3, 0,   -1 };
static const int cmu_dari_fv_028[] = { 0, 1, 0, 0, 0, 5, 1, 0,   -1 };
static const int cmu_dari_fv_029[] = { 0, 1, 0, 0, 0, 2, 12, 0,   -1 };
static const int cmu_dari_fv_030[] = { 0, 1, 0, 0, 0, 15, 12, 4,   -1 };
static const int cmu_dari_fv_031[] = { 0, 1, 0, 0, 0, 3, 1, 0,   -1 };
static const int cmu_dari_fv_032[] = { 0, 1, 0, 0, 0, 1, 1, 4,   -1 };
static const int cmu_dari_fv_033[] = { 0, 1, 0, 0, 0, 2, 1, 4,   -1 };
static const int cmu_dari_fv_034[] = { 0 };

static const int * const cmu_dari_fvtable[] = {
  cmu_dari_fv_000, 
  cmu_dari_fv_001, 
  cmu_dari_fv_002, 
  cmu_dari_fv_003, 
  cmu_dari_fv_004, 
  cmu_dari_fv_005, 
  cmu_dari_fv_006, 
  cmu_dari_fv_007, 
  cmu_dari_fv_008, 
  cmu_dari_fv_009, 
  cmu_dari_fv_010, 
  cmu_dari_fv_011, 
  cmu_dari_fv_012, 
  cmu_dari_fv_013, 
  cmu_dari_fv_014, 
  cmu_dari_fv_015, 
  cmu_dari_fv_016, 
  cmu_dari_fv_017, 
  cmu_dari_fv_018, 
  cmu_dari_fv_019, 
  cmu_dari_fv_020, 
  cmu_dari_fv_021, 
  cmu_dari_fv_022, 
  cmu_dari_fv_023, 
  cmu_dari_fv_024, 
  cmu_dari_fv_025, 
  cmu_dari_fv_026, 
  cmu_dari_fv_027, 
  cmu_dari_fv_028, 
  cmu_dari_fv_029, 
  cmu_dari_fv_030, 
  cmu_dari_fv_031, 
  cmu_dari_fv_032, 
  cmu_dari_fv_033, 
 cmu_dari_fv_034 };

DEF_STATIC_CONST_VAL_STRING(featval_0,"-");
DEF_STATIC_CONST_VAL_STRING(featval_1,"0");
DEF_STATIC_CONST_VAL_STRING(featval_2,"f");
DEF_STATIC_CONST_VAL_STRING(featval_3,"a");
DEF_STATIC_CONST_VAL_STRING(featval_4,"+");
DEF_STATIC_CONST_VAL_STRING(featval_5,"s");
DEF_STATIC_CONST_VAL_STRING(featval_6,"2");
DEF_STATIC_CONST_VAL_STRING(featval_7,"1");
DEF_STATIC_CONST_VAL_STRING(featval_8,"l");
DEF_STATIC_CONST_VAL_STRING(featval_9,"d");
DEF_STATIC_CONST_VAL_STRING(featval_10,"p");
DEF_STATIC_CONST_VAL_STRING(featval_11,"3");
DEF_STATIC_CONST_VAL_STRING(featval_12,"v");
DEF_STATIC_CONST_VAL_STRING(featval_13,"g");
DEF_STATIC_CONST_VAL_STRING(featval_14,"r");
DEF_STATIC_CONST_VAL_STRING(featval_15,"n");
DEF_STATIC_CONST_VAL_STRING(featval_16,"b");

static const cst_val * const cmu_dari_featvals[] = {
 (cst_val *)&featval_0,
 (cst_val *)&featval_1,
 (cst_val *)&featval_2,
 (cst_val *)&featval_3,
 (cst_val *)&featval_4,
 (cst_val *)&featval_5,
 (cst_val *)&featval_6,
 (cst_val *)&featval_7,
 (cst_val *)&featval_8,
 (cst_val *)&featval_9,
 (cst_val *)&featval_10,
 (cst_val *)&featval_11,
 (cst_val *)&featval_12,
 (cst_val *)&featval_13,
 (cst_val *)&featval_14,
 (cst_val *)&featval_15,
 (cst_val *)&featval_16,
 NULL };

const cst_phoneset cmu_dari_phoneset = {
  "cmu_dari",
  cmu_dari_featnames,
  cmu_dari_featvals,
  cmu_dari_phonenames,
  "pau",
  34,
  cmu_dari_fvtable
};
