/*******************************************************/
/**  Autogenerated lts rules (regex) for cmu_iq     */
/**  from wfst/    */
/*******************************************************/

#include "cst_string.h"
#include "cst_lts.h"
#include "cst_lexicon.h"

const char * const cmu_iq_lts_phone_table[195] = 
{
    "epsilon",
    "W",
    "A-N",
    "F",
    "LH",
    "MA",
    "HA",
    "HA-AX",
    "HW",
    "U-HW",
    "HB-IH",
    "HB",
    "HY",
    "IH-HY",
    "HY-IH",
    "A",
    "SD-A",
    "AX",
    "B",
    "B-IH",
    "IH-B",
    "B-AX",
    "AX-B",
    "B-SD",
    "B-U",
    "U-B",
    "TM",
    "AX-TM",
    "T-IH",
    "T",
    "AX-T",
    "T-AX",
    "SD",
    "T-U",
    "V",
    "IH-V",
    "V-SD",
    "J",
    "IH-J",
    "J-IH",
    "AX-J",
    "J-AX",
    "J-SD",
    "J-U",
    "HH",
    "IH-HH",
    "HH-IH",
    "AX-HH",
    "U-HH",
    "HH-U",
    "HH-AX",
    "X",
    "X-AX",
    "U-X",
    "AX-X",
    "X-U",
    "IH-X",
    "X-IH",
    "D",
    "D-IH",
    "IH-D",
    "U-D",
    "AX-D",
    "D-U",
    "D-SD",
    "D-AX",
    "DW-IH",
    "U-DW",
    "DW",
    "DW-AX",
    "DW-SD",
    "AX-DW",
    "R",
    "R-SD",
    "AX-R",
    "R-IH",
    "IH-R",
    "R-AX",
    "U-R",
    "R-U",
    "AX-Z",
    "IH-Z",
    "Z",
    "Z-IH",
    "Z-AX",
    "Z-SD",
    "S",
    "IH-S",
    "AX-S",
    "S-AX",
    "S-IH",
    "S-U",
    "U-S",
    "SW",
    "AX-SW",
    "SW-SD",
    "IH-SW",
    "SW-AX",
    "SW-U",
    "SW-IH",
    "SH",
    "SH-U",
    "SH-AX",
    "AX-SH",
    "IH-SH",
    "SH-SD",
    "SH-IH",
    "DH",
    "DH-IH",
    "DH-AX",
    "IH-DH",
    "DH-SD",
    "TH",
    "TH-AX",
    "AX-TH",
    "TH-U",
    "TH-IH",
    "U-TH",
    "IH-TH",
    "TH-SD",
    "ZH",
    "IH-ZH",
    "ZH-SD",
    "ZH-AX",
    "E",
    "E-IH",
    "E-AX",
    "AX-E",
    "IH-E",
    "E-U",
    "U-E",
    "G",
    "G-IH",
    "IH-G",
    "U-G",
    "G-AX",
    "G-U",
    "Q",
    "Q-U",
    "Q-AX",
    "IH-Q",
    "AX-Q",
    "Q-SD",
    "Q-IH",
    "U-Q",
    "AX-L",
    "AX-K",
    "K-SD",
    "K",
    "K-U",
    "IH-K",
    "K-AX",
    "K-IH",
    "L",
    "L-IH",
    "L-AX",
    "IH-L",
    "L-SD",
    "L-U",
    "U-L",
    "M",
    "U-M",
    "M-IH",
    "AX-M",
    "IH-M",
    "M-AX",
    "M-SD",
    "M-U",
    "N",
    "N-SD",
    "AX-N",
    "IH-N",
    "N-AX",
    "N-U",
    "N-IH",
    "H",
    "IH-H",
    "H-IH",
    "AX-H",
    "H-AX",
    "H-U",
    "U-H",
    "AM",
    "AX-AM",
    "Y",
    "Y-SD",
    "IH",
    "Y-AX",
    "IH-Y",
    "Y-IH",
    "AX-Y",
    "Y-U",
    "CH-IH",
    "GH",
    NULL
};

const char * const cmu_iq_lts_letter_table[44] = 
{
    "nothing",
    "#",
    "0",
    "_",
    "و",
    "ً",
    "ف",
    "ء",
    "آ",
    "أ",
    "ؤ",
    "إ",
    "ئ",
    "ا",
    "ب",
    "ة",
    "ت",
    "ث",
    "ج",
    "ح",
    "خ",
    "د",
    "ذ",
    "ر",
    "ز",
    "س",
    "ش",
    "ص",
    "ض",
    "ط",
    "ظ",
    "ع",
    "غ",
    "ق",
    "ك",
    "ل",
    "م",
    "ن",
    "ه",
    "ى",
    "ي",
    "چ",
    "گ",
    NULL
};

const cst_lts_addr cmu_iq_lts_letter_index[41] = 
{
    0, /* _ */
    1, /* و */
    2, /* ً */
    3, /* ف */
    4, /* ء */
    5, /* آ */
    10, /* أ */
    171, /* ؤ */
    174, /* إ */
    240, /* ئ */
    263, /* ا */
    435, /* ب */
    614, /* ة */
    761, /* ت */
    811, /* ث */
    819, /* ج */
    941, /* ح */
    1101, /* خ */
    1194, /* د */
    1380, /* ذ */
    1416, /* ر */
    1881, /* ز */
    1940, /* س */
    2115, /* ش */
    2184, /* ص */
    2260, /* ض */
    2282, /* ط */
    2396, /* ظ */
    2414, /* ع */
    2658, /* غ */
    2689, /* ق */
    2828, /* ك */
    2986, /* ل */
    3397, /* م */
    3661, /* ن */
    3817, /* ه */
    3948, /* ى */
    3995, /* ي */
    4589, /* چ */
    4590, /* گ */
    0
};

