/*******************************************************/
/**  Autogenerated phoneset trees for cmu_pashto    */
/*******************************************************/

#include "cst_string.h"
#include "cst_phoneset.h"
extern const cst_phoneset cmu_pashto_phoneset;


static const char * const cmu_pashto_featnames[] = {
 "vc",
 "vlng",
 "vheight",
 "vfront",
 "vrnd",
 "ctype",
 "cplace",
 "cvox",
 NULL };

static const char * const cmu_pashto_phonenames[] = {
 "pau",
 "@",
 "A",
 "F",
 "G",
 "N",
 "Q",
 "S",
 "U:",
 "Z",
 "a",
 "b",
 "d",
 "dH",
 "dZ",
 "dz",
 "e",
 "f",
 "g",
 "h",
 "i",
 "i:",
 "j",
 "k",
 "l",
 "m",
 "n",
 "nH",
 "o",
 "p",
 "q",
 "rH",
 "s",
 "sH",
 "t",
 "tH",
 "tS",
 "ts",
 "u",
 "w",
 "x",
 "z",
 "zH",
 NULL };

static const int cmu_pashto_fv_000[] = { 0, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_001[] = { 2, 3, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_002[] = { 2, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_003[] = { 0, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_004[] = { 0, 1, 0, 0, 0, 1, 1, 2,   -1 };
static const int cmu_pashto_fv_005[] = { 0, 1, 0, 0, 0, 1, 1, 2,   -1 };
static const int cmu_pashto_fv_006[] = { 0, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_007[] = { 0, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_008[] = { 2, 4, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_009[] = { 0, 1, 0, 0, 0, 1, 1, 2,   -1 };
static const int cmu_pashto_fv_010[] = { 2, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_011[] = { 0, 1, 0, 0, 0, 1, 1, 2,   -1 };
static const int cmu_pashto_fv_012[] = { 0, 1, 0, 0, 0, 1, 1, 2,   -1 };
static const int cmu_pashto_fv_013[] = { 0, 1, 0, 0, 0, 1, 1, 2,   -1 };
static const int cmu_pashto_fv_014[] = { 0, 1, 0, 0, 0, 1, 1, 2,   -1 };
static const int cmu_pashto_fv_015[] = { 0, 1, 0, 0, 0, 1, 1, 2,   -1 };
static const int cmu_pashto_fv_016[] = { 2, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_017[] = { 0, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_018[] = { 0, 1, 0, 0, 0, 1, 1, 2,   -1 };
static const int cmu_pashto_fv_019[] = { 0, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_020[] = { 2, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_021[] = { 2, 4, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_022[] = { 0, 1, 0, 0, 0, 1, 1, 2,   -1 };
static const int cmu_pashto_fv_023[] = { 0, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_024[] = { 0, 1, 0, 0, 0, 1, 1, 2,   -1 };
static const int cmu_pashto_fv_025[] = { 0, 1, 0, 0, 0, 1, 1, 2,   -1 };
static const int cmu_pashto_fv_026[] = { 0, 1, 0, 0, 0, 1, 1, 2,   -1 };
static const int cmu_pashto_fv_027[] = { 0, 1, 0, 0, 0, 1, 1, 2,   -1 };
static const int cmu_pashto_fv_028[] = { 2, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_029[] = { 0, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_030[] = { 0, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_031[] = { 0, 1, 0, 0, 0, 1, 1, 2,   -1 };
static const int cmu_pashto_fv_032[] = { 0, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_033[] = { 0, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_034[] = { 0, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_035[] = { 0, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_036[] = { 0, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_037[] = { 0, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_038[] = { 2, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_039[] = { 0, 1, 0, 0, 0, 1, 1, 2,   -1 };
static const int cmu_pashto_fv_040[] = { 0, 1, 0, 0, 0, 1, 1, 0,   -1 };
static const int cmu_pashto_fv_041[] = { 0, 1, 0, 0, 0, 1, 1, 2,   -1 };
static const int cmu_pashto_fv_042[] = { 0, 1, 0, 0, 0, 1, 1, 2,   -1 };
static const int cmu_pashto_fv_043[] = { 0 };

static const int * const cmu_pashto_fvtable[] = {
  cmu_pashto_fv_000, 
  cmu_pashto_fv_001, 
  cmu_pashto_fv_002, 
  cmu_pashto_fv_003, 
  cmu_pashto_fv_004, 
  cmu_pashto_fv_005, 
  cmu_pashto_fv_006, 
  cmu_pashto_fv_007, 
  cmu_pashto_fv_008, 
  cmu_pashto_fv_009, 
  cmu_pashto_fv_010, 
  cmu_pashto_fv_011, 
  cmu_pashto_fv_012, 
  cmu_pashto_fv_013, 
  cmu_pashto_fv_014, 
  cmu_pashto_fv_015, 
  cmu_pashto_fv_016, 
  cmu_pashto_fv_017, 
  cmu_pashto_fv_018, 
  cmu_pashto_fv_019, 
  cmu_pashto_fv_020, 
  cmu_pashto_fv_021, 
  cmu_pashto_fv_022, 
  cmu_pashto_fv_023, 
  cmu_pashto_fv_024, 
  cmu_pashto_fv_025, 
  cmu_pashto_fv_026, 
  cmu_pashto_fv_027, 
  cmu_pashto_fv_028, 
  cmu_pashto_fv_029, 
  cmu_pashto_fv_030, 
  cmu_pashto_fv_031, 
  cmu_pashto_fv_032, 
  cmu_pashto_fv_033, 
  cmu_pashto_fv_034, 
  cmu_pashto_fv_035, 
  cmu_pashto_fv_036, 
  cmu_pashto_fv_037, 
  cmu_pashto_fv_038, 
  cmu_pashto_fv_039, 
  cmu_pashto_fv_040, 
  cmu_pashto_fv_041, 
  cmu_pashto_fv_042, 
 cmu_pashto_fv_043 };

DEF_STATIC_CONST_VAL_STRING(featval_0,"-");
DEF_STATIC_CONST_VAL_STRING(featval_1,"0");
DEF_STATIC_CONST_VAL_STRING(featval_2,"+");
DEF_STATIC_CONST_VAL_STRING(featval_3,"a");
DEF_STATIC_CONST_VAL_STRING(featval_4,"l");

static const cst_val * const cmu_pashto_featvals[] = {
 (cst_val *)&featval_0,
 (cst_val *)&featval_1,
 (cst_val *)&featval_2,
 (cst_val *)&featval_3,
 (cst_val *)&featval_4,
 NULL };

const cst_phoneset cmu_pashto_phoneset = {
  "cmu_pashto",
  cmu_pashto_featnames,
  cmu_pashto_featvals,
  cmu_pashto_phonenames,
  "pau",
  43,
  cmu_pashto_fvtable
};
