/*******************************************************/
/**  Autogenerated phoneset trees for cmu_iq    */
/*******************************************************/

#include "cst_string.h"
#include "cst_phoneset.h"
extern const cst_phoneset cmu_iq_phoneset;


static const char * const cmu_iq_featnames[] = {
 "clst",
 "vc",
 "vlng",
 "vheight",
 "vfront",
 "vrnd",
 "ctype",
 "cplace",
 "cvox",
 "asp",
 "nuk",
 NULL };

static const char * const cmu_iq_phonenames[] = {
 "pau",
 "DA",
 "SD",
 "HB",
 "HA",
 "MA",
 "LH",
 "HY",
 "SW",
 "DW",
 "HW",
 "AX",
 "A",
 "B",
 "D",
 "DH",
 "E",
 "F",
 "FH",
 "G",
 "GH",
 "H",
 "HH",
 "IH",
 "J",
 "CH",
 "K",
 "KH",
 "L",
 "M",
 "N",
 "NN",
 "O",
 "TM",
 "P",
 "Q",
 "R",
 "S",
 "SH",
 "TH",
 "T",
 "U",
 "V",
 "W",
 "X",
 "Y",
 "AM",
 "Z",
 "ZH",
 NULL };

static const int cmu_iq_fv_000[] = { 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,   -1 };
static const int cmu_iq_fv_001[] = { 0, 2, 3, 4, 4, 0, 1, 1, 1, 1, 1,   -1 };
static const int cmu_iq_fv_002[] = { 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,   -1 };
static const int cmu_iq_fv_003[] = { 0, 0, 1, 1, 1, 1, 5, 6, 0, 0, 2,   -1 };
static const int cmu_iq_fv_004[] = { 0, 0, 1, 1, 1, 1, 5, 6, 0, 2, 2,   -1 };
static const int cmu_iq_fv_005[] = { 0, 2, 1, 1, 1, 1, 5, 6, 2, 2, 0,   -1 };
static const int cmu_iq_fv_006[] = { 0, 0, 1, 1, 1, 1, 5, 6, 2, 0, 0,   -1 };
static const int cmu_iq_fv_007[] = { 0, 0, 1, 1, 1, 1, 5, 6, 0, 2, 0,   -1 };
static const int cmu_iq_fv_008[] = { 0, 0, 1, 1, 1, 1, 7, 8, 0, 0, 0,   -1 };
static const int cmu_iq_fv_009[] = { 0, 0, 1, 1, 1, 1, 7, 9, 2, 0, 0,   -1 };
static const int cmu_iq_fv_010[] = { 0, 0, 1, 1, 1, 1, 5, 6, 2, 0, 2,   -1 };
static const int cmu_iq_fv_011[] = { 0, 2, 10, 11, 11, 0, 1, 1, 1, 1, 1,   -1 };
static const int cmu_iq_fv_012[] = { 0, 0, 1, 1, 1, 1, 5, 6, 0, 0, 0,   -1 };
static const int cmu_iq_fv_013[] = { 0, 0, 1, 1, 1, 1, 5, 3, 2, 0, 0,   -1 };
static const int cmu_iq_fv_014[] = { 0, 0, 1, 1, 1, 1, 5, 10, 2, 0, 0,   -1 };
static const int cmu_iq_fv_015[] = { 0, 0, 1, 1, 1, 1, 5, 10, 2, 0, 2,   -1 };
static const int cmu_iq_fv_016[] = { 0, 0, 1, 1, 1, 1, 7, 6, 2, 0, 2,   -1 };
static const int cmu_iq_fv_017[] = { 0, 0, 1, 1, 1, 1, 7, 9, 0, 0, 0,   -1 };
static const int cmu_iq_fv_018[] = { 0, 0, 1, 1, 1, 1, 7, 9, 0, 0, 2,   -1 };
static const int cmu_iq_fv_019[] = { 0, 0, 1, 1, 1, 1, 7, 12, 2, 0, 0,   -1 };
static const int cmu_iq_fv_020[] = { 0, 0, 1, 1, 1, 1, 7, 12, 2, 0, 2,   -1 };
static const int cmu_iq_fv_021[] = { 0, 0, 1, 1, 1, 1, 7, 6, 0, 0, 0,   -1 };
static const int cmu_iq_fv_022[] = { 0, 0, 1, 1, 1, 1, 7, 6, 0, 0, 2,   -1 };
static const int cmu_iq_fv_023[] = { 0, 2, 5, 4, 4, 0, 1, 1, 1, 1, 1,   -1 };
static const int cmu_iq_fv_024[] = { 0, 0, 1, 1, 1, 1, 5, 12, 2, 0, 0,   -1 };
static const int cmu_iq_fv_025[] = { 0, 0, 1, 1, 1, 1, 10, 8, 0, 0, 0,   -1 };
static const int cmu_iq_fv_026[] = { 0, 0, 1, 1, 1, 1, 5, 12, 0, 0, 0,   -1 };
static const int cmu_iq_fv_027[] = { 0, 0, 1, 1, 1, 1, 5, 12, 0, 0, 2,   -1 };
static const int cmu_iq_fv_028[] = { 0, 0, 1, 1, 1, 1, 13, 10, 2, 0, 0,   -1 };
static const int cmu_iq_fv_029[] = { 0, 0, 1, 1, 1, 1, 14, 3, 2, 0, 0,   -1 };
static const int cmu_iq_fv_030[] = { 0, 0, 1, 1, 1, 1, 14, 10, 2, 0, 0,   -1 };
static const int cmu_iq_fv_031[] = { 0, 0, 1, 1, 1, 1, 14, 10, 2, 0, 2,   -1 };
static const int cmu_iq_fv_032[] = { 0, 2, 9, 15, 11, 0, 1, 1, 1, 1, 1,   -1 };
static const int cmu_iq_fv_033[] = { 0, 2, 10, 11, 11, 0, 1, 1, 1, 1, 2,   -1 };
static const int cmu_iq_fv_034[] = { 0, 0, 1, 1, 1, 1, 5, 3, 0, 0, 0,   -1 };
static const int cmu_iq_fv_035[] = { 0, 0, 1, 1, 1, 1, 5, 12, 0, 0, 2,   -1 };
static const int cmu_iq_fv_036[] = { 0, 0, 1, 1, 1, 1, 13, 10, 2, 0, 0,   -1 };
static const int cmu_iq_fv_037[] = { 0, 0, 1, 1, 1, 1, 7, 10, 0, 0, 0,   -1 };
static const int cmu_iq_fv_038[] = { 0, 0, 1, 1, 1, 1, 7, 10, 0, 0, 2,   -1 };
static const int cmu_iq_fv_039[] = { 0, 0, 1, 1, 1, 1, 5, 10, 0, 0, 2,   -1 };
static const int cmu_iq_fv_040[] = { 0, 0, 1, 1, 1, 1, 5, 10, 0, 0, 0,   -1 };
static const int cmu_iq_fv_041[] = { 0, 2, 5, 4, 15, 2, 1, 1, 1, 1, 1,   -1 };
static const int cmu_iq_fv_042[] = { 0, 0, 1, 1, 1, 1, 7, 9, 0, 0, 0,   -1 };
static const int cmu_iq_fv_043[] = { 0, 0, 1, 1, 1, 1, 13, 3, 2, 0, 0,   -1 };
static const int cmu_iq_fv_044[] = { 0, 0, 1, 1, 1, 1, 7, 12, 0, 0, 0,   -1 };
static const int cmu_iq_fv_045[] = { 0, 0, 1, 1, 1, 1, 10, 8, 2, 0, 0,   -1 };
static const int cmu_iq_fv_046[] = { 0, 2, 3, 4, 4, 0, 1, 1, 1, 1, 2,   -1 };
static const int cmu_iq_fv_047[] = { 0, 0, 1, 1, 1, 1, 7, 10, 2, 0, 0,   -1 };
static const int cmu_iq_fv_048[] = { 0, 0, 1, 1, 1, 1, 7, 10, 2, 0, 2,   -1 };
static const int cmu_iq_fv_049[] = { 0 };

static const int * const cmu_iq_fvtable[] = {
  cmu_iq_fv_000, 
  cmu_iq_fv_001, 
  cmu_iq_fv_002, 
  cmu_iq_fv_003, 
  cmu_iq_fv_004, 
  cmu_iq_fv_005, 
  cmu_iq_fv_006, 
  cmu_iq_fv_007, 
  cmu_iq_fv_008, 
  cmu_iq_fv_009, 
  cmu_iq_fv_010, 
  cmu_iq_fv_011, 
  cmu_iq_fv_012, 
  cmu_iq_fv_013, 
  cmu_iq_fv_014, 
  cmu_iq_fv_015, 
  cmu_iq_fv_016, 
  cmu_iq_fv_017, 
  cmu_iq_fv_018, 
  cmu_iq_fv_019, 
  cmu_iq_fv_020, 
  cmu_iq_fv_021, 
  cmu_iq_fv_022, 
  cmu_iq_fv_023, 
  cmu_iq_fv_024, 
  cmu_iq_fv_025, 
  cmu_iq_fv_026, 
  cmu_iq_fv_027, 
  cmu_iq_fv_028, 
  cmu_iq_fv_029, 
  cmu_iq_fv_030, 
  cmu_iq_fv_031, 
  cmu_iq_fv_032, 
  cmu_iq_fv_033, 
  cmu_iq_fv_034, 
  cmu_iq_fv_035, 
  cmu_iq_fv_036, 
  cmu_iq_fv_037, 
  cmu_iq_fv_038, 
  cmu_iq_fv_039, 
  cmu_iq_fv_040, 
  cmu_iq_fv_041, 
  cmu_iq_fv_042, 
  cmu_iq_fv_043, 
  cmu_iq_fv_044, 
  cmu_iq_fv_045, 
  cmu_iq_fv_046, 
  cmu_iq_fv_047, 
  cmu_iq_fv_048, 
 cmu_iq_fv_049 };

DEF_STATIC_CONST_VAL_STRING(featval_0,"-");
DEF_STATIC_CONST_VAL_STRING(featval_1,"0");
DEF_STATIC_CONST_VAL_STRING(featval_2,"+");
DEF_STATIC_CONST_VAL_STRING(featval_3,"l");
DEF_STATIC_CONST_VAL_STRING(featval_4,"1");
DEF_STATIC_CONST_VAL_STRING(featval_5,"s");
DEF_STATIC_CONST_VAL_STRING(featval_6,"g");
DEF_STATIC_CONST_VAL_STRING(featval_7,"f");
DEF_STATIC_CONST_VAL_STRING(featval_8,"p");
DEF_STATIC_CONST_VAL_STRING(featval_9,"d");
DEF_STATIC_CONST_VAL_STRING(featval_10,"a");
DEF_STATIC_CONST_VAL_STRING(featval_11,"2");
DEF_STATIC_CONST_VAL_STRING(featval_12,"v");
DEF_STATIC_CONST_VAL_STRING(featval_13,"r");
DEF_STATIC_CONST_VAL_STRING(featval_14,"n");
DEF_STATIC_CONST_VAL_STRING(featval_15,"3");

static const cst_val * const cmu_iq_featvals[] = {
 (cst_val *)&featval_0,
 (cst_val *)&featval_1,
 (cst_val *)&featval_2,
 (cst_val *)&featval_3,
 (cst_val *)&featval_4,
 (cst_val *)&featval_5,
 (cst_val *)&featval_6,
 (cst_val *)&featval_7,
 (cst_val *)&featval_8,
 (cst_val *)&featval_9,
 (cst_val *)&featval_10,
 (cst_val *)&featval_11,
 (cst_val *)&featval_12,
 (cst_val *)&featval_13,
 (cst_val *)&featval_14,
 (cst_val *)&featval_15,
 NULL };

const cst_phoneset cmu_iq_phoneset = {
  "cmu_iq",
  cmu_iq_featnames,
  cmu_iq_featvals,
  cmu_iq_phonenames,
  "pau",
  49,
  cmu_iq_fvtable,
  0  /* not freeable */
};
